version: '3'

services:
  web1:
    build: node_app
    ports:
      - "8081:8080"
    depends_on:
      - pgdb
    environment:
      - CONNETIONSTRING=postgresql://postgres:postgres@pgdb:5432/postgres
    volumes:
            - ./node_app/src/:/opt/src/server/src/
  web2:
    build: node_app
    ports:
      - "8082:8080"
    depends_on:
      - pgdb
    environment:
      - CONNETIONSTRING=postgresql://postgres:postgres@pgdb:5432/postgres
    volumes:
            - ./node_app/src/:/opt/src/server/src/
  web3:
    build: node_app
    ports:
      - "8083:8080"
    depends_on:
      - pgdb
    environment:
      - CONNETIONSTRING=postgresql://postgres:postgres@pgdb:5432/postgres
    volumes:
            - ./node_app/src/:/opt/src/server/src/
  pgdb:
    image: "postgres"
    expose:
      - 5432

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.1/24
