version: '3'

services:
  web1:
    build: node_app
    ports:
     - "8080:8080"
    depends_on:
      - pgdb
    networks:
          app_net:
            ipv4_address: 172.18.0.2
  pgdb:
    image: "postgres"
    expose:
      - 5432
    networks:
      app_net:
        ipv4_address: 172.18.0.3

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.1/24
